# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.0.2"
          cache: true
          cache-key: flutter
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
